### ISSUE TITLE
Use radio buttons instead of drop down for group

### ISSUE THREAD

**Issue by thewildmage** [rp-magrathea/vogsphere#15]
Per:
- https://learnui.design/blog/4-rules-intuitive-ux.html#2-abd-anything-but-dropdowns
- https://tomkenny.design/articles/false-simplicity

Radio buttons wouldn't take up that much more space, they're easier to work with, and they give a clearer view of the available options.

**Comment by vicc30** [comment]
Hello! I want to collaborate! which group is exactly where is needed the radio buttons?.

**Comment by thewildmage** [comment]
@vicc30, that'd be great! It's the "member group" section of the form that needs the update. It's currently a dropdown/select, but should be converted to radio buttons instead.
