### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by thewildmage** [rp-magrathea/vogsphere#21]
- [Examples and info](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file)
- Specific points to include:
   - [ ] Class and ID naming conventions

**Comment by vicc30** [comment]
Hello! Can I help you with this?

**Comment by thewildmage** [comment]
Hello again, @vicc30! I do sincerely appreciate the offer, but I'm not sure you can help here because I don't have a good handle yet on what all should be included in this documentation. Thank you so much for offering though! :heart:

**Comment by thewildmage** [comment]
Magrathea has a global/default CONTRIBUTING file now. This isn't needed anymore.
